#!/usr/bin/env python3
"""Generate Gin route metadata from the dereferenced OpenAPI contract."""

from pathlib import Path

import yaml


ROOT = Path(__file__).resolve().parents[2]
CONTRACT = ROOT / "contracts" / "openapi.bundle.deref.yaml"
OUTPUT = ROOT / "internal" / "adapters" / "inbound" / "http" / "v1" / "routes_gen.go"
METHODS = ("get", "post", "put", "patch", "delete", "head", "options")

# Route groups are the operationId namespaces documented in docs/backend/api.md.
# Adding an entry here also requires registering a middleware chain for it.
GROUP_CONSTANTS = {
    "health": "GroupHealth",
    "auth": "GroupAuth",
    "me": "GroupMe",
    "self": "GroupSelf",
    "public": "GroupPublic",
    "admin": "GroupAdmin",
    "analytics": "GroupAnalytics",
}


def gin_path(path: str) -> str:
    parts = []
    parameter_index = 0
    for part in path.split("/"):
        if part.startswith("{") and part.endswith("}"):
            parameter_index += 1
            parts.append(f":param{parameter_index}")
        else:
            parts.append(part)
    return "/".join(parts)


def group_constant(operation_id: str) -> str:
    namespace = operation_id.split(".")[0]
    if namespace not in GROUP_CONSTANTS:
        raise SystemExit(
            f"operationId {operation_id!r} declares unknown route group {namespace!r}; "
            "add it to GROUP_CONSTANTS, to the chain registry in "
            "internal/adapters/inbound/http/router.go, and to docs/backend/api.md"
        )
    return GROUP_CONSTANTS[namespace]


def auth_constant(operation: dict, default_security: list) -> str:
    security = operation.get("security", default_security)
    if not security:
        return "AuthNone"
    # An empty requirement next to a scheme makes credentials optional.
    if any(not requirement for requirement in security):
        return "AuthOptional"
    return "AuthRequired"


def main() -> None:
    document = yaml.safe_load(CONTRACT.read_text())
    default_security = document.get("security", [])
    routes = {}
    for path, path_item in document.get("paths", {}).items():
        for method in METHODS:
            operation = path_item.get(method)
            if not operation:
                continue
            operation_id = operation.get("operationId")
            if not operation_id:
                raise SystemExit(f"{method.upper()} {path} is missing an operationId")
            key = (method.upper(), gin_path(path))
            if key in routes:
                raise SystemExit(
                    f"{key[0]} {key[1]} resolves to two operations: "
                    f"{routes[key][0]} and {operation_id}"
                )
            routes[key] = (
                operation_id,
                group_constant(operation_id),
                auth_constant(operation, default_security),
            )

    lines = [
        "// Code generated by scripts/contracts/generate_go_routes.py; DO NOT EDIT.",
        "",
        "package v1",
        "",
        "var Routes = []Route{",
    ]
    for (method, path), (operation_id, group, auth) in sorted(routes.items()):
        lines.append(
            f'\t{{Method: "{method}", Path: "{path}", OperationID: "{operation_id}", '
            f"Group: {group}, Auth: {auth}}},"
        )
    lines.extend(["}", ""])
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text("\n".join(lines))
    print(f"generated {len(routes)} unique routes in {OUTPUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
